# Generated by Django 5.1.1 on 2024-11-08 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastos',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.categorias'),
        ),
        migrations.AlterField(
            model_name='gastos',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
